### ISSUE TITLE
Printing decoded secrets should not add a newline

### ISSUE THREAD

**Issue by corneliusweig** [elsesiy/kubectl-view-secret#1]
When decoding a secret, `view-secret` should not add a newline, as this changes the content in the secret. For example, when storing a password, it makes a difference if the string is `my-password` or `my-password\n`

See https://github.com/elsesiy/kubectl-view-secret/blob/f4fac7a9933fc5d5117ac277c6b6a779c9d08334/pkg/cmd/view-secret.go#L120

---

Also, when decoding all key/value pairs in a secret, it would be nice to separate those visually by an extra newline between the entries.

**Comment by elsesiy** [comment]
@corneliusweig Thanks for pointing this out. So I'm going to remove the newline when printing the individual secret but will add an additional newline when decoding all secrets. Sound good?

Output will look as follows:
```
	kubectl view-secret <secret> <key> 
	output
```

And

```
	kubectl view-secret <secret> -a
	KEY=VALUE

	KEY=VALUE

	KEY=VALUE
```

If I understand the intent behind removing the newline for the first case correctly, users may want to use the output in scripts that would break if a newline is added, right? In the second case the newlines don't really matter as the user wouldn't use the output directly?

**Comment by corneliusweig** [comment]
@elsesiy Exactly, so well put!
