### ISSUE TITLE
Problem with docs

### ISSUE THREAD

**Issue by towolf** [elsesiy/kubectl-view-secret#2]
```
$ kubectl view-secret default-token-5pgsw
Error: unknown command "view-secret" for "kubectl"
Run 'kubectl --help' for usage.

$ kubectl view secret default-token-5pgsw
Multiple sub keys found. Specify another argument, one of:
-> ca.crt
-> namespace
-> token

$ kubectl version --short
Client Version: v1.16.2

```

Are you sure the command is `view-secret`?

**Comment by elsesiy** [comment]
@towolf Thanks for opening this issue. Can you please elaborate on what you did in order to install the binary? In general you have to take the following steps:
1. Download release
2. `chmod +x binary`
3. `cp binary somewhere/in/$PATH`
4. `kubectl view-secret -h`

or you install it via `krew` for which I haven't added the usage instructions to the readme yet.

**Comment by elsesiy** [comment]
Oh I just notice the issue sorry, what platform are you operating on?

**Comment by towolf** [comment]
No, I think you may have missed how that works. The dashes are removed by kubectl. See the docs here:

https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/#naming-a-plugin

**Comment by towolf** [comment]
Linux.

**Comment by elsesiy** [comment]
@towolf That's odd, on Mac using the very same `kubectl version` I'm able to call it with `-` in between. Did you manually install it or via `krew`? I have to follow-up  with them on this..

**Comment by towolf** [comment]
No,I just downloaded the binary end extracted into my PATH.

I don't see the point in krew, it makes something simple complicated.

**Comment by towolf** [comment]
```
$ which kubectl-view-secret 
/home/towolf/.local/bin/kubectl-view-secret
```

**Comment by elsesiy** [comment]
Got it, thanks! I'm not sure where the difference comes from at this point but I'll follow-up on this and maybe just update the manual usage instructions to cp `kubectl-view-secret somewhere/in/path/kubectl-view_secret` which according to the docs should fix it..

**Comment by towolf** [comment]
Ah, so you *want* the command to be `view-secret`.  I thought the docs were wrong ...

**Comment by elsesiy** [comment]
@towolf Yes since `view-secret` was an existing command we decided to update the existing spec instead of creating a new plugin. I initially called it kubectl-decode which is not adhering to krews naming guidelines..

**Comment by elsesiy** [comment]
I just checked the symlink created by krew which is indeed:
`kubectl-view_secret -> /Users/elsesiy/.krew/store/view-secret/v0.3.0/kubectl-view-secret`

**Comment by klaernie** [comment]
I just got bitten by the same problem - after downloading the binary from the release.

May I suggest renaming the command itself to `kubectl-view_secret` - so both `cmd/kubectl-view-secret.go` and in the makefile? This should stop people not knowledgeable in how kubectl searches for plugin binaries making the same mistake.
