### ISSUE TITLE
support sort values and do not print empty lines

### ISSUE THREAD

**Issue by elonzh** [elsesiy/kubectl-view-secret#20]
I'm almost always using view-secret with this command:

```shell
kubectl view-secret <name> --all | sort | grep "\S"
```

that is because the `view-secret` output has empty lines and keeps keys unordered.

I hope we can support sort keys and without empty lines as default for better usability and portability(like windows support).

**Comment by elsesiy** [comment]
Hi @elonzh,
I have to think about this a bit more. Could you provide some more details on your use-case pls and why you think these features should be natively supported?

Thanks.

**Comment by elonzh** [comment]
I use the command to generate env files and those env files will be used for [kustomize secretGenerator](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/secretgenerator/) and local development.

**Comment by elsesiy** [comment]
@elonzh I just released version `0.9.0` which addresses both issues described here, please check it out and let me know if you need anything else!

**Comment by elonzh** [comment]
Thanks for your work!
