### ISSUE TITLE
Add support for impersonating groups with flag

### ISSUE THREAD

**Issue by pratikkumar-mohite** [elsesiy/kubectl-view-secret#42]
Adding support for impersonation of groups by passing --as-group through to kubectl exec/get secret cli. We use impersonation as cluster-admins to elevate access to cluster secrets and cluster exec, kubectl supports this with the --as-group flag and supporting this in view-secret makes this much easier to utilize with kubernetes RBAC.

```bash
kubectl view-secret --as=pratikkumar.mohite --as-group=system:masters  default-secret                                                         
Error: unknown flag: --as-group
```

**Comment by pratikkumar-mohite** [comment]
@elsesiy can you assign this to me, also I've raised the PR https://github.com/elsesiy/kubectl-view-secret/pull/43 could you verify and merge?

**Comment by elsesiy** [comment]
Implemented via https://github.com/elsesiy/kubectl-view-secret/pull/43
