### ISSUE TITLE
New line getting trimmed when using `view-secret -a`

### ISSUE THREAD

**Issue by ANGkeith** [elsesiy/kubectl-view-secret#44]
![image](https://github.com/elsesiy/kubectl-view-secret/assets/28011783/31e96366-350f-468c-896b-adaab49bd3e9)

Hi, thanks for the plugin. I would like to check, is there any rational for the trimSpaces? Can we remove it ?

https://github.com/elsesiy/kubectl-view-secret/blob/v0.12.0/pkg/cmd/view-secret.go#L178

**Comment by elsesiy** [comment]
Hey, thanks for the issue!
We added this via https://github.com/elsesiy/kubectl-view-secret/pull/36. Could you tell me more about the issue you're facing with the current implementation? Thanks!

**Comment by ANGkeith** [comment]
@elsesiy 
not too sure how to phrase it, 


input: 
foo: "some-secret\n\n\n"

when i run `kubectl view-secret my-secret -a`
expect:
```
foo: 'some-secret


'
```

but, actual:
```
foo: 'some-secret'
```
